### PR TITLE
fix: remove systemjs duplicate imports

### LINKED ISSUE #57: Open in Plunker doesn't work in IE due to duplicated imports
### Description
The DatePicker demos wouldn't work in Plunker when opened in IE due to duplicated `kendo-angular-intl` package imports.

The `kendo-angular-intl` auto-import is required due to `kendoDate` pipe usage in the demos.

We will need to filter the static imports that we include

### PR DESCRIPTION
**Pull request by Raisolution**
Closes #57

### CODE REVIEW

File: docs-public/snippets.js [hunk 1]
```diff
@@ -713,7 +721,13 @@ function openInPlunkr(listing) {
...
         appModuleImports:   $.map(directives, toModuleImport).join("\n"),
         appModules:         $.map(directives, function(dir) { return dir.import }).join(", "),
-        systemjsPackages:   $.map(directives.filter(function(dir) { return dir.module.indexOf('@angular') != 0 }), toSystemJsPackage).join("\n")
+        systemjsPackages:   $.map(directives.filter(function(dir) { return dir.module.indexOf('@angular') != 0 })
+                                            .concat(systemJsDefaultKendoPackages)
+                                            .filter(function(value, index, self) {
+                                                return self.findIndex(function(current, currentI) {
+                                                    return current.module === value.module;
+                                                }) === index;
+                                            }), toSystemJsPackage).join("\n" + Array(7).join(" "))
```
Comment (gyoshev) [inline docs-public/snippets.js]: Seems quite involved. I'd suggest moving this as a standalone statement, or at least extracting the second `filter` callback as `unique` to make it more understandable.
